# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SachKo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SachKo

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'

  target 'SachKo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SachKoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SachKo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SachKo-tvOS


end
